language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: wCgJfZXfkxqyX5Bf/E5fKs5y5XZNaPA0m/vBoWJf8EetydAKXYv2JtGHYqC3UOFuh5E0S/dbIg6AwHqLrkxTHWQL9HWWTwkobqWt0IYQv4kYTUmZ4xg42HxJ5cH0M5VNxZkSghl/IaLrJl6RFP7Hq0NON6pAf9206421HhKOVLlIp0Q4ZQ9w8U9UAAATMoa/HR7v1N7J+9BW/ms4QfUpO1fxe1HYxaxL9+HTCsiXf2elwSdNdZGYsLttClZVDvUSHUOL5fj63RcC8cBVuyCFKd1W/Q/g+OijPR/oW++05jqKMezUfG4znLhynDbQBdwcJz2nXcvAiKwL7sbTqip6/9HX7MXX47qovKLFX+68VdLOKYBxBZSnY7LsCQGUWudG2WPBPWHFOuGVavVZomwayLQ6E0A0rGbJKPQ8nu+/+2uoB8YxxCbw4UY3MsrY6oUF++zVKEtSvV0uqgBo+BjOnmfETjMYR3zCNTgzLr77Vlby5hj+TZcJvp9M+po8UovXAzyk5xjxzTUeIUO9wbCKPh86ldg1HsnxIBcJk7KoM/ebe7lmfCTPse6tmjsfQsBQHhGHlfXCxp0Rl0yHCiF6u/PCdEnd+TqAbfJ3wXdAkoDFU70VShGgdLyz+VyB7ytCYE56sTO+S9hp9Od4YsPxF+/6SzAp5DqGroIyWQsnOuo=
  app: pure-anchorage-91323
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bin/rake db:migrate RAILS_ENV=test
