language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: kxH5B0VZ07deInc0rc2dLT0Hx+fphyQtybSTclMMX3JPu1KStsA5hljGaFVOUvo5Yp6/8qYu29zSBR1JQ671/ExOOOKqZpkuaU2l0UBombQvwfSOKkSmZ8Co/e7xlM58pCEoyg2JC42Q5eXhKByBCQm7qCZbb+ncyM7GTtmbyRR1ZLTfM4MjomWgoq+G+Oco5HDldkMPXo8MKYh5WxQR+8NjBPwiDJc3Flgvi+o/Q/eFhYEpY3oH5Wlvj8g5Gm0QKgWzEdYk5lwcrh0S0FUz+qBhaU902yOejP0+rBmdnPOEUV5CRwRPq1dASre++FORsDPUyRU5znHyFTfKlue+QUY8kp5x0nU7YV6H3WC6ycsFd0sn1ypC3UuUa9+LACiEA4dGfNXD+Xar9ORKypfEU4MhsUtZpdRBnqoR4p/npNHNM9JcR7MTb3Ge4SPxlBgnJZFDAYZYvV7uAJXq3sO8j1zUyBlaRosj3dLNtAWgMFLoJ5A0l821nR0A4EtKpnSVnnFT8yM+YFlAdgHEVfGZHeySfHrEJwqyaKnI7JJSjIqlRlXk+kalrR0krAHeHaE1+IW2dtQvc9AO0N30dUe79kVUFnB7aBOKEfQOqX8yHX4sBvhQ9GYJn/a/nRX0q4aAB2TnFchzmJJkeeLADE9WyfcKkU4UJct+A0UPG8t2+NU=
  app: nyamco_enpit_team
  on:
    repo: hiroak/nyamco_enpit_team

addons:

  postgresql: "9.3"

before_script:

  - psql -c 'create database travis_ci_test;' -U postgres

  - cp config/database.yml.travis config/database.yml

  - bin/rake db:migrate RAILS_ENV=test
